In [4]:
import numpy as np

class ModelExample:
    def normalize(self, data, metadata):
        mask = metadata.get("mask", np.ones_like(metadata["mean"], dtype=bool))
        return np.where(
            mask,
            (data - metadata["mean"]) / (metadata["std"] + 1e-8),
            data,
        )

# Example setup
state_data = np.array([
    [10, 20, 30],  # Time step 1
    [40, 50, 60]   # Time step 2
])
metadata = {
    "mean": np.array([5, 25, 50]),
    "std": np.array([5, 5, 10]),
    "mask": np.array([True, True, True])
}

# Instantiate the model example class
model_example = ModelExample()

# Normalize the state data
normalized_state_data = model_example.normalize(state_data, metadata)

# Print the original and normalized state data
print("Original State Data:\n", state_data)
print("\nNormalized State Data:\n", normalized_state_data)


[[10 20 30]
 [40 50 60]]
Original State Data:
 [[10 20 30]
 [40 50 60]]

Normalized State Data:
 [[ 1.         -1.         -2.        ]
 [ 6.99999999  4.99999999  1.        ]]


In [5]:
np.stack([1],[2])

TypeError: 'list' object cannot be interpreted as an integer